In [1]:
print("hello")

hello

In [8]:
import pandas as pd
import numpy as np

In [4]:
titanic =pd.read_csv("Titanic Dataset.csv")

In [5]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [12]:
data = {'creatures': ['Eagles', 'Eagles', 'Ducks', 'Herons', 'Herons', 'Eagles', 'Ducks', 'Eagles', 'Herons', 'Herons', 'Eagles'], 
        'weight': [2.0, 5, 3.0, np.nan, 7, 2.5, 6, np.nan, 9, 3, 2.0], 
        'frequency': [1, 3, 2, 5, 2, 3, 1, 3, 4, 2, 1], 
        'status': ['no', 'no', 'yes', np.nan, 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no'], 
        'height': [1.2, 2.5, 1.8, 3.0, 2.2, 1.9, 2.6, 1.4, 2.8, 2.3, 1.1], 
        'region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'East', 'South'], 
        'danger_level': ['low', 'medium', 'high', 'low', 'high', 'medium', 'high', 'low', 'medium', 'high', 'low']}

labels = ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p']

df=pd.DataFrame(data, index=labels)
print(df)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [15]:
df.info()
print("\n Summary statics")
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, x to p
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   creatures     11 non-null     object
 1   weight        9 non-null      float64
 2   frequency     11 non-null     int64
 3   status        10 non-null     object
 4   height        11 non-null     float64
 5   region        11 non-null     object
 6   danger_level  11 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1004.0+ bytes

 Summary statics

         weight  frequency     height
count  9.000000  11.000000  11.000000
mean   4.388889   2.454545   2.072727
std    2.497221   1.293340   0.646670
min    2.000000   1.000000   1.100000
25%    2.500000   1.500000   1.600000
50%    3.000000   2.000000   2.200000
75%    6.000000   3.000000   2.550000
max    9.000000   5.000000   3.000000

In [ ]:
#III.	Write a program to display every alternate row of the DataFrame (starting from index 0).
df.iloc[::2]

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
t     Ducks     6.0          1    yes     2.6   East         high
r    Herons     9.0          4    yes     2.8  North       medium
p    Eagles     2.0          1     no     1.1  South          low

In [21]:
#IV.	Write a program to display only rows at index positions 1st, 3rd, and 7th from columns creatures and weight of the DataFrame
df.iloc[[1, 3, 7], [0, 1]]

  creatures  weight
y    Eagles     5.0
w    Herons     NaN
s    Eagles     NaN

In [22]:
print(df.loc[df['frequency'] <4])

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low